-- Nearby: Supabase schema + seed. Paste this whole file into the Supabase SQL editor and Run.

create table if not exists places (
  id text primary key,
  name text not null,
  layer text[] not null,
  category text,
  address text,
  neighborhood text,
  hours text,
  phone text,
  note text,
  bring text,
  lat double precision,
  lng double precision
);
alter table places enable row level security;
drop policy if exists "public read places" on places;
create policy "public read places" on places for select using (true);

create table if not exists suggestions (
  id uuid primary key default gen_random_uuid(),
  name text,
  category text,
  address text,
  note text,
  contact text,
  created_at timestamptz default now()
);
alter table suggestions enable row level security;
drop policy if exists "public add suggestion" on suggestions;
create policy "public add suggestion" on suggestions for insert with check (true);

-- 31 verified Detroit places
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('capuchin-meldrum','Capuchin Soup Kitchen — Meldrum Meal Site','{food}','Free meal','1264 Meldrum St, Detroit, MI 48207','East side / near Gratiot & Mt. Elliott','Breakfast Mon–Fri 8:30–9:30am; Lunch Mon–Fri 11:00am–1:00pm','(313) 579-2100','Free full-course hot meals for anyone, no questions asked.','Nothing needed — walk in.',42.34885,-83.01171) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('capuchin-conner','Capuchin Soup Kitchen — Conner Meal Site','{food}','Free meal','4390 Conner St, Detroit, MI 48215','East side / Conner & Mack','Breakfast Mon–Fri 8:30–9:30am (call to confirm lunch)','(313) 579-2100','Free daily meals; second Capuchin meal site on the east side.','Nothing needed — walk in.',42.38664,-82.96965) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('focus-hope-food','Focus: HOPE — Food for Seniors','{food}','Food pantry','1300 Oakman Blvd, Detroit, MI 48238','Oakman Blvd / Northwest Detroit','Mon–Thu 8:00am–4:00pm; Fri 8:00am–12:00pm','(313) 494-4600','Monthly free food packages, primarily for income-eligible seniors 60+.','Photo ID and proof of Detroit address; age 60+.',42.40035,-83.12069) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('eastern-market','Eastern Market — Saturday Market','{food}','EBT market','2934 Russell St, Detroit, MI 48207','Eastern Market district','Saturdays 6:00am–4:00pm year-round','','Accepts EBT/SNAP + Double Up Food Bucks (match up to $50/day) on Michigan produce.','Your EBT/Bridge card — ask at the Welcome Center.',42.34904,-83.04188) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('peoples-coop','Detroit People''s Food Co-op','{food}','EBT market','8324 Woodward Ave, Detroit, MI 48202','North End / Woodward','Hours vary — call to confirm','','Full-service grocery co-op accepting EBT/SNAP and Double Up Food Bucks.','Your EBT/Bridge card.',42.37712,-83.07731) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('peaches-greens','Peaches & Greens','{food}','EBT market','8838 3rd Ave, Detroit, MI 48202','North End','Hours vary — call to confirm','','Neighborhood produce market accepting EBT and Double Up Food Bucks.','Your EBT/Bridge card.',42.33573,-83.05981) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('prince-valley','Prince Valley Market','{food}','EBT market','5931 Michigan Ave, Detroit, MI 48210','Southwest Detroit / Michigan Ave','Hours vary — call to confirm','','Grocery store accepting EBT/SNAP and Double Up Food Bucks on fresh produce.','Your EBT/Bridge card.',42.3304,-83.11604) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('glory-outer','Glory Supermarket — Outer Drive','{food}','EBT market','8000 W Outer Dr, Detroit, MI 48235','Northwest Detroit / Outer Drive','Hours vary — call to confirm','','Grocery store accepting EBT/SNAP and Double Up Food Bucks.','Your EBT/Bridge card.',42.41939,-83.21689) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('accounting-aid','Accounting Aid Society','{money}','Free tax prep','3031 W Grand Blvd, Detroit, MI 48202','New Center / Fisher Building area','Seasonal — free VITA tax sites run Jan–Apr; office Mon–Fri','(313) 556-1920','Free IRS-certified (VITA) tax prep; helps claim EITC & Home Heating Credit.','Photo ID, Social Security cards, W-2s/1099s, last year''s return.',42.37019,-83.07629) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('wayne-connect','Wayne Metro CONNECT Center','{utility,money}','Utility help','5555 Conner Ave, Detroit, MI 48213','East side / Conner','Hours vary — call to confirm','(313) 388-9799','Walk-in hub for energy assistance, water help, and basic-needs programs.','Photo ID, most recent utility bill, proof of income.',42.39644,-82.98983) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('wayne-woodward','Wayne Metro — Woodward Office','{housing,money}','Rent help','7310 Woodward Ave, Detroit, MI 48202','New Center / Woodward','Hours vary — call to confirm','(313) 388-9799','Rent/eviction help, HOPE property-tax exemption, and Detroit Tax Relief Fund intake.','Photo ID, lease, court/eviction papers, proof of income.',42.37087,-83.07281) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('thaw','THAW — The Heat and Warmth Fund','{utility,money}','Utility help','535 Griswold St, Detroit, MI 48226','Downtown Detroit','Apply by phone Mon–Fri 8:00am–4:45pm','1-800-866-8429','Emergency help with past-due or shut-off gas/electric bills. Phone-based — not a walk-in site.','Account numbers, shutoff notice, proof of income (over the phone).',42.32942,-83.04696) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('dpl-main','Detroit Public Library — Main Library','{kids}','Library','5201 Woodward Ave, Detroit, MI 48202','Midtown / Cultural Center','Mon 10:00am–6:00pm; Tue–Wed 12:00pm–8:00pm; Thu–Sat 10:00am–6:00pm; Sun 1:00pm–5:00pm','(313) 481-1300','Free kids/teen programs, story times, HYPE Teen Center, free computers and Wi-Fi.','Nothing needed; bring proof of address to get a free library card.',42.35835,-83.06686) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('dpl-redford','Detroit Public Library — Redford Branch','{kids}','Library','21200 Grand River Ave, Detroit, MI 48219','Northwest / Grand River & W. McNichols','Mon 12:00pm–8:00pm; Tue 10:00am–6:00pm; Wed 12:00pm–8:00pm; Thu 10:00am–6:00pm','(313) 481-1820','Neighborhood branch with children''s programs and free computer/Wi-Fi access.','Nothing needed to visit.',42.41401,-83.25005) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('dpl-jefferson','Detroit Public Library — Thomas Jefferson Branch','{kids}','Library','12350 E Outer Dr, Detroit, MI 48224','East side / E. Outer Dr & E. Warren','Hours vary — call to confirm','','Branch with weekly kids'' story times, reading clubs, and teen activities.','Nothing needed to visit.',42.40407,-82.93725) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('rec-coleman','Coleman A. Young Recreation Center','{kids}','Rec center','2751 Robert Bradby Dr, Detroit, MI 48207','District 5 / southeast side','Hours vary — call to confirm','(313) 224-1100','City recreation center with youth programs, gym, and activities.','Nothing needed; some programs require a rec pass.',42.34588,-83.02476) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('rec-nwac','Northwest Activities Center','{kids}','Rec center','18100 Meyers Rd, Detroit, MI 48235','Northwest Detroit / Meyers & Curtis','Hours vary — call to confirm','(313) 224-1100','Large community/recreation center; also hosts a Detroit at Work career center.','Nothing needed to visit.',42.42299,-83.169) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('rec-kemeny','Kemeny Recreation Center','{kids}','Rec center','2260 S Fort St, Detroit, MI 48217','Southwest / Boynton','Hours vary — call to confirm','(313) 224-1100','City recreation center with youth and family programming.','Nothing needed to visit.',42.27358,-83.15719) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('daw-meyers','Detroit at Work Career Center — Meyers','{jobs}','Career center','18100 Meyers, Detroit, MI 48235','Northwest Detroit (inside Northwest Activities Center)','Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)','(313) 962-9675','Free career coaching, job search help, training referrals, and unemployment (UIA) help.','Photo ID, resume if you have one, Social Security number.',42.42299,-83.169) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('daw-ewarren','Detroit at Work Career Center — E. Warren','{jobs}','Career center','18017 E Warren Ave, Detroit, MI 48224','East side / E. Warren','Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)','(313) 962-9675','Free career advising, job placement, and unemployment insurance assistance.','Photo ID, resume if you have one.',42.41002,-82.91931) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('daw-michigan','Detroit at Work Career Center — Michigan Ave','{jobs}','Career center','9301 Michigan Ave, Detroit, MI 48210','Southwest Detroit / Michigan Ave','Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)','(313) 962-9675','Free career center with advising, training referrals, and UIA help.','Photo ID, resume if you have one.',42.328,-83.15397) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('daw-conner','Detroit at Work Job Search Hub — Conner','{jobs}','Career center','5901 Conner St, Detroit, MI 48213','East side / Conner','Mon–Fri 8:00am–5:00pm','(313) 962-9675','Walk-in job search hub with computers and staff to help apply for jobs.','Photo ID.',42.39414,-82.98507) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('svdp-gratiot','Society of St. Vincent de Paul Detroit','{utility}','Utility help','3000 Gratiot Ave, Detroit, MI 48207','McDougall-Hunt (near Gratiot & Mack)','Hours vary — call to confirm','(313) 393-2930','Energy and rent assistance (Michigan Energy Assistance Program) for low-income households; a DTE referral agency.','Photo ID, utility bill/shutoff notice, proof of income.',42.3561031,-83.0293199) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('matrix-parsons','Matrix Human Services','{utility}','Utility help','120 Parsons St, Detroit, MI 48201','Midtown (off Woodward, near Parsons)','Hours vary — call to confirm','(313) 831-1000','Community action agency offering State Emergency Relief and energy/utility assistance intake.','Photo ID, proof of income, utility bill.',42.3482094,-83.0596712) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('salvarmy-conner','The Salvation Army — Conner Creek Corps','{utility}','Utility help','3000 Conner St, Detroit, MI 48215','East side (Conner & Charlevoix area)','Hours vary — call to confirm','','Corps community center providing emergency assistance, including help with heat and utility bills.','Photo ID, proof of address and income.',42.3796998,-82.9645565) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('uchc-riverplace','United Community Housing Coalition','{housing}','Eviction help','300 River Place Dr, Suite 1200, Detroit, MI 48207','East Riverfront (River Place complex)','Mon–Fri 8:30am–5:00pm (by appointment; call first)','(313) 963-3310','Prevents eviction, foreclosure, and homelessness; tenant counseling and back-tax help.','Photo ID, lease, any court/eviction papers, proof of income.',42.336605,-83.017718) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('lakeshore-2ndave','Lakeshore Legal Aid — Eviction Prevention','{housing}','Legal aid','2727 Second Ave, Suite 318, Detroit, MI 48201','Midtown / Cass Park','Apply by phone at (888) 783-8190','(888) 783-8190','Free civil legal help for low-income tenants facing eviction; intake via the Counsel & Advocacy Law Line.','Court papers, lease, proof of income (over the phone).',42.3400396,-83.0616698) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('cots-peterboro','COTS — Coalition On Temporary Shelter','{housing}','Shelter intake','26 Peterboro St, Suite 100, Detroit, MI 48201','Midtown (Peterboro, near Woodward)','Hours vary — call to confirm','(313) 831-3777','Emergency shelter and housing services for families and individuals experiencing homelessness.','Photo ID if you have one; call ahead for intake.',42.3452882,-83.0575637) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('chass-fort','CHASS Center','{health}','Free clinic','5635 West Fort St, Detroit, MI 48209','Southwest Detroit','Hours vary — call to confirm','(313) 849-3920','Federally qualified health center; medical, dental, and behavioral care on a sliding scale, insured or not.','Photo ID; insurance if you have it (not required).',42.308757,-83.0969844) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('covenant-michave','Covenant Community Care — Michigan Ave','{health}','Free clinic','5716 Michigan Ave, Detroit, MI 48210','Southwest Detroit (Michigan Ave corridor)','Hours vary — call to confirm','','Nonprofit clinic offering low-cost medical, dental, and mental health care on a sliding scale.','Photo ID; insurance if you have it (not required).',42.3315192,-83.1134536) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
insert into places (id,name,layer,category,address,neighborhood,hours,phone,note,bring,lat,lng) values ('dchc-eriverside','Detroit Community Health Connection','{health}','Free clinic','13901 E Jefferson Ave, Detroit, MI 48215','East side (E Jefferson, near Chalmers)','Hours vary — call to confirm','(313) 822-0900','Federally qualified health center; family medicine and community care regardless of ability to pay.','Photo ID; insurance if you have it (not required).',42.3718282,-82.9480426) on conflict (id) do update set name=excluded.name, layer=excluded.layer, category=excluded.category, address=excluded.address, neighborhood=excluded.neighborhood, hours=excluded.hours, phone=excluded.phone, note=excluded.note, bring=excluded.bring, lat=excluded.lat, lng=excluded.lng;
