// Nearby Now — data layer. Real, verified Detroit resources.
// coords are [lat, lng]; filled from OpenStreetMap geocoding.
window.CATS = [
  { key:"food",    name:"Food",            icon:'<path d="M4 3v7a2 2 0 0 0 2 2h0V3M6 3v18M14 3c-1 2-2 4-2 6a2 2 0 0 0 2 2v10"/>' },
  { key:"utility", name:"Utility & bills", icon:'<path d="M13 2 4 14h7l-1 8 9-12h-7l1-8Z"/>' },
  { key:"housing", name:"Housing",         icon:'<path d="M4 11 12 4l8 7M6 10v9h12v-9"/>' },
  { key:"kids",    name:"Kids & family",   icon:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-3 2.5-5 6-5s6 2 6 5M15 20c0-2 1-3.5 3-3.5s3 1.5 3 3.5"/>' },
  { key:"jobs",    name:"Jobs",            icon:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18"/>' },
  { key:"money",   name:"Money & benefits",icon:'<circle cx="12" cy="12" r="9"/><path d="M12 7v10M9.5 9.5c0-1 1-1.5 2.5-1.5s2.5.7 2.5 1.7-1 1.3-2.5 1.3-2.5.5-2.5 1.5 1 1.5 2.5 1.5 2.5-.5 2.5-1.5"/>' },
  { key:"health",  name:"Health",          icon:'<path d="M12 21s-7-4.35-9.5-9C1 9 2.5 5 6 5c2 0 3 1.5 6 4 3-2.5 4-4 6-4 3.5 0 5 4 3.5 7-2.5 4.65-9.5 9-9.5 9Z"/>' },
  { key:"transit", name:"Transit",         icon:'<rect x="6" y="3" width="12" height="14" rx="2"/><path d="M6 12h12M9 21l1.5-3M15 21l-1.5-3M9 7h6"/>', soon:true },
  { key:"goods",   name:"Goods",           icon:'<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18M16 10a4 4 0 0 1-8 0"/>', soon:true }
];

window.CAT_ICON = {"Free meal":0,"Food pantry":0,"EBT market":'<circle cx="8" cy="21" r="1"/><circle cx="18" cy="21" r="1"/><path d="M2 3h3l2.4 12.3a2 2 0 0 0 2 1.7h8.6a2 2 0 0 0 2-1.6L23 7H6"/>',"Free tax prep":5,"Utility help":1,"Rent help":2,"Eviction help":2,"Legal aid":2,"Shelter intake":2,"Library":'<path d="M4 5a2 2 0 0 1 2-2h4v18H6a2 2 0 0 1-2-2V5ZM14 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4V3Z"/>',"Rec center":3,"Career center":4,"Free clinic":6};

window.PLACES = [
  {id:"capuchin-meldrum",name:"Capuchin Soup Kitchen — Meldrum Meal Site",layer:["food"],category:"Free meal",address:"1264 Meldrum St, Detroit, MI 48207",neighborhood:"East side / near Gratiot & Mt. Elliott",hours:"Breakfast Mon–Fri 8:30–9:30am; Lunch Mon–Fri 11:00am–1:00pm",phone:"(313) 579-2100",note:"Free full-course hot meals for anyone, no questions asked.",bring:"Nothing needed — walk in.",coords:null},
  {id:"capuchin-conner",name:"Capuchin Soup Kitchen — Conner Meal Site",layer:["food"],category:"Free meal",address:"4390 Conner St, Detroit, MI 48215",neighborhood:"East side / Conner & Mack",hours:"Breakfast Mon–Fri 8:30–9:30am (call to confirm lunch)",phone:"(313) 579-2100",note:"Free daily meals; second Capuchin meal site on the east side.",bring:"Nothing needed — walk in.",coords:null},
  {id:"focus-hope-food",name:"Focus: HOPE — Food for Seniors",layer:["food"],category:"Food pantry",address:"1300 Oakman Blvd, Detroit, MI 48238",neighborhood:"Oakman Blvd / Northwest Detroit",hours:"Mon–Thu 8:00am–4:00pm; Fri 8:00am–12:00pm",phone:"(313) 494-4600",note:"Monthly free food packages, primarily for income-eligible seniors 60+.",bring:"Photo ID and proof of Detroit address; age 60+.",coords:null},
  {id:"eastern-market",name:"Eastern Market — Saturday Market",layer:["food"],category:"EBT market",address:"2934 Russell St, Detroit, MI 48207",neighborhood:"Eastern Market district",hours:"Saturdays 6:00am–4:00pm year-round",phone:"",note:"Accepts EBT/SNAP + Double Up Food Bucks (match up to $50/day) on Michigan produce.",bring:"Your EBT/Bridge card — ask at the Welcome Center.",coords:null},
  {id:"peoples-coop",name:"Detroit People's Food Co-op",layer:["food"],category:"EBT market",address:"8324 Woodward Ave, Detroit, MI 48202",neighborhood:"North End / Woodward",hours:"Hours vary — call to confirm",phone:"",note:"Full-service grocery co-op accepting EBT/SNAP and Double Up Food Bucks.",bring:"Your EBT/Bridge card.",coords:null},
  {id:"peaches-greens",name:"Peaches & Greens",layer:["food"],category:"EBT market",address:"8838 3rd Ave, Detroit, MI 48202",neighborhood:"North End",hours:"Hours vary — call to confirm",phone:"",note:"Neighborhood produce market accepting EBT and Double Up Food Bucks.",bring:"Your EBT/Bridge card.",coords:null},
  {id:"prince-valley",name:"Prince Valley Market",layer:["food"],category:"EBT market",address:"5931 Michigan Ave, Detroit, MI 48210",neighborhood:"Southwest Detroit / Michigan Ave",hours:"Hours vary — call to confirm",phone:"",note:"Grocery store accepting EBT/SNAP and Double Up Food Bucks on fresh produce.",bring:"Your EBT/Bridge card.",coords:null},
  {id:"glory-outer",name:"Glory Supermarket — Outer Drive",layer:["food"],category:"EBT market",address:"8000 W Outer Dr, Detroit, MI 48235",neighborhood:"Northwest Detroit / Outer Drive",hours:"Hours vary — call to confirm",phone:"",note:"Grocery store accepting EBT/SNAP and Double Up Food Bucks.",bring:"Your EBT/Bridge card.",coords:null},
  {id:"accounting-aid",name:"Accounting Aid Society",layer:["money"],category:"Free tax prep",address:"3031 W Grand Blvd, Detroit, MI 48202",neighborhood:"New Center / Fisher Building area",hours:"Seasonal — free VITA tax sites run Jan–Apr; office Mon–Fri",phone:"(313) 556-1920",note:"Free IRS-certified (VITA) tax prep; helps claim EITC & Home Heating Credit.",bring:"Photo ID, Social Security cards, W-2s/1099s, last year's return.",coords:null},
  {id:"wayne-connect",name:"Wayne Metro CONNECT Center",layer:["utility","money"],category:"Utility help",address:"5555 Conner Ave, Detroit, MI 48213",neighborhood:"East side / Conner",hours:"Hours vary — call to confirm",phone:"(313) 388-9799",note:"Walk-in hub for energy assistance, water help, and basic-needs programs.",bring:"Photo ID, most recent utility bill, proof of income.",coords:null},
  {id:"wayne-woodward",name:"Wayne Metro — Woodward Office",layer:["housing","money"],category:"Rent help",address:"7310 Woodward Ave, Detroit, MI 48202",neighborhood:"New Center / Woodward",hours:"Hours vary — call to confirm",phone:"(313) 388-9799",note:"Rent/eviction help, HOPE property-tax exemption, and Detroit Tax Relief Fund intake.",bring:"Photo ID, lease, court/eviction papers, proof of income.",coords:null},
  {id:"thaw",name:"THAW — The Heat and Warmth Fund",layer:["utility","money"],category:"Utility help",address:"535 Griswold St, Detroit, MI 48226",neighborhood:"Downtown Detroit",hours:"Apply by phone Mon–Fri 8:00am–4:45pm",phone:"1-800-866-8429",note:"Emergency help with past-due or shut-off gas/electric bills. Phone-based — not a walk-in site.",bring:"Account numbers, shutoff notice, proof of income (over the phone).",coords:null},
  {id:"dpl-main",name:"Detroit Public Library — Main Library",layer:["kids"],category:"Library",address:"5201 Woodward Ave, Detroit, MI 48202",neighborhood:"Midtown / Cultural Center",hours:"Mon 10:00am–6:00pm; Tue–Wed 12:00pm–8:00pm; Thu–Sat 10:00am–6:00pm; Sun 1:00pm–5:00pm",phone:"(313) 481-1300",note:"Free kids/teen programs, story times, HYPE Teen Center, free computers and Wi-Fi.",bring:"Nothing needed; bring proof of address to get a free library card.",coords:null},
  {id:"dpl-redford",name:"Detroit Public Library — Redford Branch",layer:["kids"],category:"Library",address:"21200 Grand River Ave, Detroit, MI 48219",neighborhood:"Northwest / Grand River & W. McNichols",hours:"Mon 12:00pm–8:00pm; Tue 10:00am–6:00pm; Wed 12:00pm–8:00pm; Thu 10:00am–6:00pm",phone:"(313) 481-1820",note:"Neighborhood branch with children's programs and free computer/Wi-Fi access.",bring:"Nothing needed to visit.",coords:null},
  {id:"dpl-jefferson",name:"Detroit Public Library — Thomas Jefferson Branch",layer:["kids"],category:"Library",address:"12350 E Outer Dr, Detroit, MI 48224",neighborhood:"East side / E. Outer Dr & E. Warren",hours:"Hours vary — call to confirm",phone:"",note:"Branch with weekly kids' story times, reading clubs, and teen activities.",bring:"Nothing needed to visit.",coords:null},
  {id:"rec-coleman",name:"Coleman A. Young Recreation Center",layer:["kids"],category:"Rec center",address:"2751 Robert Bradby Dr, Detroit, MI 48207",neighborhood:"District 5 / southeast side",hours:"Hours vary — call to confirm",phone:"(313) 224-1100",note:"City recreation center with youth programs, gym, and activities.",bring:"Nothing needed; some programs require a rec pass.",coords:null},
  {id:"rec-nwac",name:"Northwest Activities Center",layer:["kids"],category:"Rec center",address:"18100 Meyers Rd, Detroit, MI 48235",neighborhood:"Northwest Detroit / Meyers & Curtis",hours:"Hours vary — call to confirm",phone:"(313) 224-1100",note:"Large community/recreation center; also hosts a Detroit at Work career center.",bring:"Nothing needed to visit.",coords:null},
  {id:"rec-kemeny",name:"Kemeny Recreation Center",layer:["kids"],category:"Rec center",address:"2260 S Fort St, Detroit, MI 48217",neighborhood:"Southwest / Boynton",hours:"Hours vary — call to confirm",phone:"(313) 224-1100",note:"City recreation center with youth and family programming.",bring:"Nothing needed to visit.",coords:null},
  {id:"daw-meyers",name:"Detroit at Work Career Center — Meyers",layer:["jobs"],category:"Career center",address:"18100 Meyers, Detroit, MI 48235",neighborhood:"Northwest Detroit (inside Northwest Activities Center)",hours:"Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)",phone:"(313) 962-9675",note:"Free career coaching, job search help, training referrals, and unemployment (UIA) help.",bring:"Photo ID, resume if you have one, Social Security number.",coords:null},
  {id:"daw-ewarren",name:"Detroit at Work Career Center — E. Warren",layer:["jobs"],category:"Career center",address:"18017 E Warren Ave, Detroit, MI 48224",neighborhood:"East side / E. Warren",hours:"Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)",phone:"(313) 962-9675",note:"Free career advising, job placement, and unemployment insurance assistance.",bring:"Photo ID, resume if you have one.",coords:null},
  {id:"daw-michigan",name:"Detroit at Work Career Center — Michigan Ave",layer:["jobs"],category:"Career center",address:"9301 Michigan Ave, Detroit, MI 48210",neighborhood:"Southwest Detroit / Michigan Ave",hours:"Mon–Fri 8:00am–5:00pm (Thu until 7:00pm)",phone:"(313) 962-9675",note:"Free career center with advising, training referrals, and UIA help.",bring:"Photo ID, resume if you have one.",coords:null},
  {id:"daw-conner",name:"Detroit at Work Job Search Hub — Conner",layer:["jobs"],category:"Career center",address:"5901 Conner St, Detroit, MI 48213",neighborhood:"East side / Conner",hours:"Mon–Fri 8:00am–5:00pm",phone:"(313) 962-9675",note:"Walk-in job search hub with computers and staff to help apply for jobs.",bring:"Photo ID.",coords:null},
  {id:"svdp-gratiot",name:"Society of St. Vincent de Paul Detroit",layer:["utility"],category:"Utility help",address:"3000 Gratiot Ave, Detroit, MI 48207",neighborhood:"McDougall-Hunt (near Gratiot & Mack)",hours:"Hours vary — call to confirm",phone:"(313) 393-2930",note:"Energy and rent assistance (Michigan Energy Assistance Program) for low-income households; a DTE referral agency.",bring:"Photo ID, utility bill/shutoff notice, proof of income.",coords:[42.3561031,-83.0293199]},
  {id:"matrix-parsons",name:"Matrix Human Services",layer:["utility"],category:"Utility help",address:"120 Parsons St, Detroit, MI 48201",neighborhood:"Midtown (off Woodward, near Parsons)",hours:"Hours vary — call to confirm",phone:"(313) 831-1000",note:"Community action agency offering State Emergency Relief and energy/utility assistance intake.",bring:"Photo ID, proof of income, utility bill.",coords:[42.3482094,-83.0596712]},
  {id:"salvarmy-conner",name:"The Salvation Army — Conner Creek Corps",layer:["utility"],category:"Utility help",address:"3000 Conner St, Detroit, MI 48215",neighborhood:"East side (Conner & Charlevoix area)",hours:"Hours vary — call to confirm",phone:"",note:"Corps community center providing emergency assistance, including help with heat and utility bills.",bring:"Photo ID, proof of address and income.",coords:[42.3796998,-82.9645565]},
  {id:"uchc-riverplace",name:"United Community Housing Coalition",layer:["housing"],category:"Eviction help",address:"300 River Place Dr, Suite 1200, Detroit, MI 48207",neighborhood:"East Riverfront (River Place complex)",hours:"Mon–Fri 8:30am–5:00pm (by appointment; call first)",phone:"(313) 963-3310",note:"Prevents eviction, foreclosure, and homelessness; tenant counseling and back-tax help.",bring:"Photo ID, lease, any court/eviction papers, proof of income.",coords:[42.3366050,-83.0177180]},
  {id:"lakeshore-2ndave",name:"Lakeshore Legal Aid — Eviction Prevention",layer:["housing"],category:"Legal aid",address:"2727 Second Ave, Suite 318, Detroit, MI 48201",neighborhood:"Midtown / Cass Park",hours:"Apply by phone at (888) 783-8190",phone:"(888) 783-8190",note:"Free civil legal help for low-income tenants facing eviction; intake via the Counsel & Advocacy Law Line.",bring:"Court papers, lease, proof of income (over the phone).",coords:[42.3400396,-83.0616698]},
  {id:"cots-peterboro",name:"COTS — Coalition On Temporary Shelter",layer:["housing"],category:"Shelter intake",address:"26 Peterboro St, Suite 100, Detroit, MI 48201",neighborhood:"Midtown (Peterboro, near Woodward)",hours:"Hours vary — call to confirm",phone:"(313) 831-3777",note:"Emergency shelter and housing services for families and individuals experiencing homelessness.",bring:"Photo ID if you have one; call ahead for intake.",coords:[42.3452882,-83.0575637]},
  {id:"chass-fort",name:"CHASS Center",layer:["health"],category:"Free clinic",address:"5635 West Fort St, Detroit, MI 48209",neighborhood:"Southwest Detroit",hours:"Hours vary — call to confirm",phone:"(313) 849-3920",note:"Federally qualified health center; medical, dental, and behavioral care on a sliding scale, insured or not.",bring:"Photo ID; insurance if you have it (not required).",coords:[42.3087570,-83.0969844]},
  {id:"covenant-michave",name:"Covenant Community Care — Michigan Ave",layer:["health"],category:"Free clinic",address:"5716 Michigan Ave, Detroit, MI 48210",neighborhood:"Southwest Detroit (Michigan Ave corridor)",hours:"Hours vary — call to confirm",phone:"",note:"Nonprofit clinic offering low-cost medical, dental, and mental health care on a sliding scale.",bring:"Photo ID; insurance if you have it (not required).",coords:[42.3315192,-83.1134536]},
  {id:"dchc-eriverside",name:"Detroit Community Health Connection",layer:["health"],category:"Free clinic",address:"13901 E Jefferson Ave, Detroit, MI 48215",neighborhood:"East side (E Jefferson, near Chalmers)",hours:"Hours vary — call to confirm",phone:"(313) 822-0900",note:"Federally qualified health center; family medicine and community care regardless of ability to pay.",bring:"Photo ID; insurance if you have it (not required).",coords:[42.3718282,-82.9480426]}
];

// Coordinates from OpenStreetMap (Nominatim), merged by id.
(function(){
  var C={"capuchin-meldrum":[42.34885,-83.01171],"capuchin-conner":[42.38664,-82.96965],"focus-hope-food":[42.40035,-83.12069],"eastern-market":[42.34904,-83.04188],"peoples-coop":[42.37712,-83.07731],"peaches-greens":[42.33573,-83.05981],"prince-valley":[42.33040,-83.11604],"glory-outer":[42.41939,-83.21689],"accounting-aid":[42.37019,-83.07629],"wayne-connect":[42.39644,-82.98983],"wayne-woodward":[42.37087,-83.07281],"thaw":[42.32942,-83.04696],"dpl-main":[42.35835,-83.06686],"dpl-redford":[42.41401,-83.25005],"dpl-jefferson":[42.40407,-82.93725],"rec-coleman":[42.34588,-83.02476],"rec-nwac":[42.42299,-83.16900],"rec-kemeny":[42.27358,-83.15719],"daw-meyers":[42.42299,-83.16900],"daw-ewarren":[42.41002,-82.91931],"daw-michigan":[42.32800,-83.15397],"daw-conner":[42.39414,-82.98507]};
  window.PLACES.forEach(function(p){ if(C[p.id]) p.coords=C[p.id]; });
})();
